# Other configs
root_dir: '../input/happy-whale-and-dolphin'
save_dir: ''
title_run: 'baseline'
save_last_model: True
load_model: False
wandb_logging: True
n_fold: 6
fold: 1


# Model related hyperparameters
model_name: "tf_efficientnet_b0_ns"
n_epochs: 3
img_size: 448
num_classes: 15587
embedding_size: 512
train_batch_size: 32
val_batch_size: 32
lr: 1e-4
device: "cuda:0"
num_workers: 16

# ArcFace hyperparameters
s: 30.0
m: 0.50
ls_eps: 0.0
easy_margin: False