# Other configs
root_dir: '/home/otabek.nazarov/Downloads/kaggle/whales_modified_data/cropped'
save_dir: '/home/otabek.nazarov/Downloads/kaggle/whales-identifier/saved'
mode: 'cropped'
title_run: 'cropped_effb4'
save_last_model: True
load_model: False
wandb_logging: True
n_fold: 6
fold: 1


# Model related hyperparameters
model_name: "tf_efficientnet_b4"
n_epochs: 6
img_size: 384
num_classes: 15587
embedding_size: 512
train_batch_size: 8
val_batch_size: 4
lr: 3e-4
device: "cuda"
num_workers: 16

# ArcFace hyperparameters
s: 30.0
m: 0.30
ls_eps: 0.0
easy_margin: False

# Inference hyperparameters
pred_model_path: '/home/otabek.nazarov/Downloads/kaggle/whales-identifier/saved/cropped_baseline_best_model_weights.pt'
num_neighbors: 50
test_batch_size: 16
hnsw_M: 64
hnsw_ef: 500
new_id_thresh_dist: 0.5